--!strict

local PlayerAttributeKeys = {
	COINS = "coins",
	IS_UNLOCKED_FIRE = "isUnlockedFire",
	IS_UNLOCKED_NATURE = "isUnlockedNature",
	IS_UNLOCKED_AIR = "isUnlockedAir",
	IS_UNLOCKED_WATER = "isUnlockedWater",
	LEVEL_FIRE = "levelFire",
	LEVEL_NATURE = "levelNature",
	LEVEL_WATER = "levelWater",
	LEVEL_AIR = "levelAir",
	XP_FIRE = "xpFire",
	XP_NATURE = "xpNature",
	XP_WATER = "xpWater",
	XP_AIR = "xpAir",
	GEMS_FIRE = "gemsFire",
	GEMS_NATURE = "gemsNature",
	GEMS_WATER = "gemsWater",
	GEMS_AIR = "gemsAir",
	APPLY_FLAME_FIRE = "applyFlameFire",
	APPLY_FLAME_NATURE = "applyFlameNature",
	APPLY_FLAME_WATER = "applyFlameWater",
	APPLY_FLAME_AIR = "applyFlameAir",

	BACKGROUND_MUSIC_ENABLED = "backgroundMusicEnabled",
	SOUND_EFFECTS_ENABLED = "backgroundMusicEnabled",
}

return PlayerAttributeKeys
