--!strict

local PlayerAttributeKeys = {
	COINS = "coins",
	TOTAL_DRAGON_INCOME = "totalDragonIncome",
	INCOME_PER_SECOND = "incomePerSecond",
	REBIRTH_LEVEL = "rebirthLevel",
	REBIRTH_CURRENT_INCOME_MULT = "rebirthCurrentIncomeMult",
	REBIRTH_CURRENT_LUCK_MULT = "rebirthCurrentLuckMult",
	REBIRTH_NEXT_COST = "rebirthNextCost",
	REBIRTH_NEXT_INCOME_MULT = "rebirthNextIncomeMult",
	REBIRTH_NEXT_LUCK_MULT = "rebirthNextLuckMult",
	REBIRTH_NEXT_REQUIRED_PET_NAME = "rebirthNextRequiredPetName",
	IS_UNLOCKED_FIRE = "isUnlockedFire",
	IS_UNLOCKED_NATURE = "isUnlockedNature",
	IS_UNLOCKED_AIR = "isUnlockedAir",
	IS_UNLOCKED_WATER = "isUnlockedWater",
	LEVEL_FIRE = "levelFire",
	LEVEL_NATURE = "levelNature",
	LEVEL_WATER = "levelWater",
	LEVEL_AIR = "levelAir",
	XP_FIRE = "xpFire",
	XP_NATURE = "xpNature",
	XP_WATER = "xpWater",
	XP_AIR = "xpAir",
	GEMS_FIRE = "gemsFire",
	GEMS_NATURE = "gemsNature",
	GEMS_WATER = "gemsWater",
	GEMS_AIR = "gemsAir",
	APPLY_FLAME_FIRE = "applyFlameFire",
	APPLY_FLAME_NATURE = "applyFlameNature",
	APPLY_FLAME_WATER = "applyFlameWater",
	APPLY_FLAME_AIR = "applyFlameAir",

	BACKGROUND_MUSIC_ENABLED = "backgroundMusicEnabled",
	SOUND_EFFECTS_ENABLED = "backgroundMusicEnabled",
}

return PlayerAttributeKeys
